name: Windows DLL Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Fix CMake minimum version
        shell: pwsh
        run: |
          $fixedLines = @()
          Get-Content CMakeLists.txt | ForEach-Object {
            if ($_ -match 'cmake_minimum_required\(VERSION 2\.6\)') {
              $fixedLines += 'cmake_minimum_required(VERSION 3.5)'
            } else {
              $fixedLines += $_
            }
          }
          $fixedLines | Set-Content -NoNewline CMakeLists.txt

      - name: Configure with CMake (DLL)
        run: |
          cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Upload DLL and import library
        uses: actions/upload-artifact@v4
        with:
          name: libyaml-windows-dll
          path: |
            build/Release/libyaml.dll
            build/Release/libyaml.lib
            include/yaml.h
